---
fixtures:
  repositories:
    provision:
      repo: 'https://github.com/h0tw1r3/provision.git'
      branch: 'fix-docker-cp'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
  forge_modules:
    apt: 'puppetlabs/apt'
    stdlib: 'puppetlabs/stdlib'
    yumrepo_core: 'puppetlabs/yumrepo_core'
