---
.rubocop.yml:
  default_configs:
    inherit_from: ".rubocop_todo.yml"
    AllCops:
      Include:
        - "rakelib/*.rake"
      Exclude:
        - ".modules/**/*"
    Style/SingleLineMethods:
      Exclude:
        - "rakelib/test.rake"
Rakefile:
  default_disabled_lint_checks:
    - '140chars'
.gitignore:
  paths:
    - .modules/
    - .resource_types/
    - bolt-debug.log
    - .plan_cache.json
    - .plugin_cache.json
    - .task_cache.json
    - .rerun.json
    - .terraform/
    - .terraform*lock.hcl
    - Puppetfile
    - pdk.yaml
.pdkignore:
  paths:
    - /provision.yaml
spec/default_facts.yml:
  delete: true
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 100
Gemfile:
  optional:
    ':debug':
      - gem: puppet-catalog_rspec
        git: https://github.com/h0tw1r3/puppet-catalog_rspec.git
  overrides:
    - gem: puppetlabs_spec_helper
      version: '~> 7.0'
    - gem: puppet_litmus
      git: https://github.com/h0tw1r3/puppet_litmus.git
      branch: h0tw1r3
      platforms: [ 'ruby', 'x64_mingw' ]
